name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

env:
  CIBW_TEST_COMMAND: >
    python -c
    "from hatch_showcase.fib import fibonacci;
    assert fibonacci(32) == 2178309
    "
  CIBW_SKIP: >
    pp*

jobs:
  binary-wheels-standard:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.0
      env:
        CIBW_ARCHS_MACOS: x86_64

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

  pure-python-wheel-and-sdist:
    name: Build a pure Python wheel and source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build
      run: python -m build
      env:
        HATCH_BUILD_NO_HOOKS: 'true'

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  binary-wheels-arm:
    name: Build Linux wheels for ARM
    runs-on: ubuntu-latest
    # Very slow, no need to run on PRs
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
      ||
      (github.event_name == 'create' && github.event.ref_type == 'tag')

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.0
      env:
        CIBW_ARCHS_LINUX: aarch64

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: wheelhouse/*.whl
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - binary-wheels-standard
    - pure-python-wheel-and-sdist
    - binary-wheels-arm
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && github.event.ref_type == 'tag'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
