name: publish

on:
  push:
    tags:
    - v*

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
    - name: Download Python artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        branch: master
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Download binaries
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        branch: master
        name: standalone
        path: bin

    - name: Add binary assets to current release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*
